# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик в датчике"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/4/
Content-Type: application/json

{
  "description": "Датчик в утке, утка в зайце"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 4,
  "temperature": 36.6
}

###

# получение информации по датчику
GET {{baseUrl}}/sensor/4/
Content-Type: application/json
